ports:
  INMAA: Chennai
  INNSA: Nhava Sheva
  INMUN: Mundra
  INCOK: Cochin
  INVTZ: Visakhapatnam
  NLRTM: Rotterdam
  DEHAM: Hamburg
  BEANR: Antwerp
  GBFXT: Felixstowe
  ITGOA: Genoa
  ESBCN: Barcelona
  AEJEA: Jebel Ali
  SGSIN: Singapore
